# Generated by Django 5.0.2 on 2024-02-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionLuis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familiares',
        ),
    ]
