# Generated by Django 5.0.2 on 2024-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionLuis', '0002_rename_familia_familiares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
